# Generated by Django 5.2.17 on 2026-08-16 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='CARD', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
