# Generated by Django 5.2.17 on 2026-08-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionsettings',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionsettings',
            name='onboarding_step',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
