# Generated by Django 5.2.17 on 2026-08-16 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_limit', models.PositiveIntegerField(default=500)),
                ('faculty_limit', models.PositiveIntegerField(default=50)),
                ('storage_limit_gb', models.PositiveIntegerField(default=10)),
                ('admin_limit', models.PositiveIntegerField(default=5)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial Mode'), ('ACTIVE', 'Active Paid'), ('PAST_DUE', 'Past Due / Unpaid'), ('CANCELED', 'Canceled'), ('SUSPENDED', 'Suspended')], default='TRIAL', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('next_billing_date', models.DateField()),
                ('is_trial', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.institution')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_students', models.PositiveIntegerField(default=0)),
                ('current_faculty', models.PositiveIntegerField(default=0)),
                ('current_storage_bytes', models.BigIntegerField(default=0)),
                ('current_admins', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='tenants.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
