# Generated by Django 5.2.17 on 2026-08-16 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('examinations', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_marks', models.FloatField(default=0.0)),
                ('theory_marks', models.FloatField(default=0.0)),
                ('practical_marks', models.FloatField(default=0.0)),
                ('assignment_marks', models.FloatField(default=0.0)),
                ('attendance_marks', models.FloatField(default=0.0)),
                ('total_marks', models.FloatField(default=0.0)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('grade_point', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Saved'), ('SUBMITTED', 'Submitted to HOD'), ('APPROVED', 'Approved by HOD'), ('REJECTED', 'Rejected / Needs Correction'), ('LOCKED', 'Locked by Exam Cell')], default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to=settings.AUTH_USER_MODEL)),
                ('exam_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='examinations.examregistration')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.institution')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.subject')),
            ],
            options={
                'verbose_name_plural': 'Marks',
                'constraints': [models.UniqueConstraint(fields=('exam_registration', 'subject'), name='unique_marks_per_registration_subject')],
            },
        ),
    ]
