# Generated by Django 5.2.17 on 2026-08-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('marks_obtained', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Backlog'), ('CLEARED', 'Cleared / Passed'), ('PENDING', 'Pending Examination')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevaluationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('fee_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('EVALUATED', 'Evaluated'), ('COMPLETED', 'Completed / Published')], default='APPLIED', max_length=20)),
                ('old_marks', models.FloatField(default=0.0)),
                ('new_marks', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
