# Generated by Django 5.2.17 on 2026-08-16 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('backlogs', '0001_initial'),
        ('examinations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='cleared_in_examination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_backlogs', to='examinations.examination'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.institution'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlogs', to='academics.semester'),
        ),
    ]
