# Generated by Django 5.2.17 on 2026-08-16 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('backlogs', '0002_initial'),
        ('marks', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlogs', to='students.student'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlogs', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='revaluationapplication',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_revaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revaluationapplication',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='tenants.institution'),
        ),
        migrations.AddField(
            model_name='revaluationapplication',
            name='marks_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluation_applications', to='marks.marks'),
        ),
        migrations.AddField(
            model_name='revaluationapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revaluation_applications', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='backlog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student', 'subject', 'status'), name='unique_active_backlog_per_subject'),
        ),
    ]
